application: ieatandshop
version: 1
runtime: go
api_version: go1

handlers:

- url: /fonts
  static_dir: public/fonts

- url: /stylesheets/vendor/img
  static_dir: public/images/vendor/img
  
- url: /stylesheets
  static_dir: public/stylesheets
  
- url: /javascripts
  static_dir: public/javascripts
  
- url: /scripts
  static_dir: src/controllers
  
- url: /(.*\.(gif|png|jpg|ico))
  static_files: public/images/\1
  upload: images/(.*\.(gif|png|jpg|ico))
  
- url: /.*
  script: _go_app